spooling-manager.name=filesystem
fs.s3.enabled=true
fs.location=s3://spooling/
s3.endpoint=http://garage:3900/
s3.region=garage
s3.aws-access-key=GKAIOTRINOTESTKEY
s3.aws-secret-key=aiotrinoaiotrinoaiotrinoaiotrinoaiotrinoaiotrinoaiotrinoaiotrino
s3.path-style-access=true
# Disable segment encryption to allow HTTP connections to S3 (Garage in dev)
fs.segment.encryption=false
